version: '3'

services:
  servidor1:
    build: ./servidor1
    container_name: servidor1
    ports:
      - 5001:5000
    environment:
      - MYSQL_HOST=maestro1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=db_informacion
      - MYSQL_PORT=3306
    networks:
      - redapp

  servidor2:
    build: ./servidor2
    container_name: servidor2
    ports:
      - 5002:5000
    environment:
      - MYSQL_HOST=maestro1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=db_informacion
      - MYSQL_PORT=3306
    networks:
      - redapp

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - servidor1
      - servidor2
    networks:
      - redapp

  maestro1:
    image: mysql:8.0
    container_name: maestro1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_informacion
    ports:
      - 3306:3306
    volumes:
      - ./mysql/maestro1.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - redapp

  maestro2:
    image: mysql:8.0
    container_name: maestro2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./mysql/maestro2.cnf:/etc/mysql/conf.d/zz-maestro2.cnf
    depends_on:
      - maestro1
    networks:
      - redapp

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOSTS=maestro1,maestro2
    networks:
      - redapp

networks:
  redapp:
    driver: bridge